language: php

php:
  - 5.5
  - 5.6
  - 7.0
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

services:
  - mysql
  - redis-server

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry phpenv config-rm xdebug.ini
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.2.0"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --dev --prefer-dist --no-interaction
# codeception
  - travis_retry composer global require "codeception/codeception:^2.0" "codeception/specify" "codeception/verify"
# setup application:
  - |
    cp .env.dist .env
    sed -i s/root/travis/ .env
    cp vhost.conf.dist vhost.conf
    sed -i s/yii2-starter-kit\.dev/localhost:8080/ .env

  - |
    composer exec codecept build -- -c tests/codeception/common
    composer exec codecept build -- -c tests/codeception/backend
    composer exec codecept build -- -c tests/codeception/frontend
    composer exec codecept build -- -c tests/codeception/console

before_script:
  - mysql -e 'CREATE DATABASE `yii2-starter-kit`;';
  - php tests/codeception/bin/yii app/setup --interactive=0

script:
  - |
    php -S localhost:8080 > /dev/null 2>&1 &
    composer exec codecept run -- -c tests