app:
  build: docker/php
  working_dir: /app
  volumes:
    - ./:/app
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  links:
    - db
    - mailcatcher
  env_file:
    - .env

nginx:
  image: nginx:1.12-alpine
  ports:
    - "80:80"
  volumes:
    - ./:/app
    - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
  links:
    - app

mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - "1080:1080"

db:
  image: mysql:5.7
  volumes:
    - /var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: yii2-starter-kit
    MYSQL_USER: ysk_dbu
    MYSQL_PASSWORD: ysk_pass
